# Generated by Django 5.2.7 on 2025-11-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.BigIntegerField(db_index=True, null=True)),
                ('version', models.IntegerField(null=True)),
                ('account_id', models.CharField(db_index=True, max_length=64, null=True)),
                ('instance_id', models.CharField(db_index=True, max_length=64, null=True)),
                ('srcaddr', models.CharField(db_index=True, max_length=64, null=True)),
                ('dstaddr', models.CharField(db_index=True, max_length=64, null=True)),
                ('protocol', models.CharField(db_index=True, max_length=32, null=True)),
                ('packets', models.BigIntegerField(null=True)),
                ('bytes', models.BigIntegerField(null=True)),
                ('starttime', models.BigIntegerField(db_index=True, null=True)),
                ('endtime', models.BigIntegerField(db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=32, null=True)),
                ('log_status', models.CharField(max_length=32, null=True)),
                ('srcport', models.IntegerField(db_index=True, null=True)),
                ('dstport', models.IntegerField(db_index=True, null=True)),
                ('file_name', models.CharField(db_index=True, max_length=255)),
                ('raw_line', models.TextField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['srcaddr', 'dstaddr', 'action'], name='events_even_srcaddr_3e54d6_idx'), models.Index(fields=['starttime', 'endtime'], name='events_even_startti_c74f65_idx')],
            },
        ),
    ]
